"""empty message

Revision ID: 6b856864cc9a
Revises: 8fd9c80393d4
Create Date: 2020-11-27 00:56:08.987837

"""

# revision identifiers, used by Alembic.
revision = '6b856864cc9a'
down_revision = '8fd9c80393d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('username', 'email')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', 'email', name='user_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
